### PR TITLE
RE #69- Second Attempt: Create mentions autocomplete UI and functionality 

### PR DESCRIPTION
**Pull request by jimBeaux27**
Created a fresh branch for this

### CODE REVIEW

**Comment by tomastiminskas** [comment]
Fixes and adjustments needed:

IMG_9659
- If just a few aliases are suggested, the view should show at the bottom (just above the text field or the podcast player bar if it's present)

IMG_9660
- Aliases view should fill the entire space between the chat header bar and the bottom bar (text field and podcast player bar): right now there is a space at the top and at the bottom. I think you should make this view constrained to the chat UITableView and check where we are setting contentInset for the chat table and set the same for the suggestions table (I think that would work)
- Let's make colors more in sync with app colors (you can use Body for background and Divider for lines)

LOGIC: 
- Finally if you tap `@a` you are seeing all aliases containing `a`, but I think you should see all aliases starting with `a`

**Comment by jimBeaux27** [comment]
Ok quick update. Should be able to finish by today:
- _If just a few aliases are suggested, the view should show at the bottom (just above the text field or the podcast player bar if it's present)_ 
    -> ok I assume that means you want the tableview to populate from the bottom UP. Does that mean the "most relevant name" goes closest to the text box (total inversion of the default top to bottom paradigm)?

- _Aliases view should fill the entire space between the chat header bar and the bottom bar (text field and podcast player bar): right now there is a space at the top and at the bottom. I think you should make this view constrained to the chat UITableView and check where we are setting contentInset for the chat table and set the same for the suggestions table (I think that would work)_
  -> you're correct I tried this and it seems to work

- _Let's make colors more in sync with app colors (you can use Body for background and Divider for lines)_
 -> not totally sure I follow this one. Do you just mean you want the background to be whatever color the chat background is? What do you mean by Divider for lines?

- _Finally if you tap @a you are seeing all aliases containing a, but I think you should see all aliases starting with a_
 -> OK. I assume this means you want to return anything that matches up to the letter typed for example. @a -> anon123, alex456 but @al -> alex456 only. Correct?

**Comment by jimBeaux27** [comment]
@tomastiminskas nevermind RE color scheme I see now the UIColor.swift file and see what you mean. 

Thanks,
Jim

**Comment by tomastiminskas** [comment]
@jimBeaux27 yes to all!

**Comment by jimBeaux27** [comment]
@tomastiminskas almost done. I am stuck on trying to invert the population of the tableView (bottom up). Seems a lot more complex than I would think. Do you have any tips on how to accomplish this? I tried this: https://stackoverflow.com/questions/28105905/how-to-populate-uitableview-from-the-bottom-upwards but it seems to mess with the constraints and move the tablecells out of view...

**Review by tomastiminskas — APPROVED** [review]

**Pull request merged**
