### PR TITLE
Jc/add/tagalog translations

### PR DESCRIPTION
**Pull request by jimBeaux27**

### CODE REVIEW

**Comment by tomastiminskas** [comment]
@jimBeaux27 what's the state of philippine translations on all platforms (iOS, Mac, Android)? Do we have a translator working on them? Or they are finished? 

If we have someone reviewing and working on final translations, it would be good to ask him to consider the length of the english texts and try to find a translation with a similar length to prevent the issue about text going out of container element boundaries

**Comment by jimBeaux27** [comment]
sure @tomastiminskas 
- iOS is ready
- Android, PR is made however I have no way to do QA testing. I would consider it ready for QA
- Mac does not have any translations attempted yet. Should I start?

**Comment by tomastiminskas** [comment]
@jimBeaux27 please go ahead with Mac translation and with replacement of shorter translations from Khar on iOS and Android

**Comment by jimBeaux27** [comment]
Ok. As far as I can tell in my tests, all of the problematic long strings are already replaced on the iOS PR (this one). Do you see any problem areas I should be aware of?

For Android I suspect this is likewise the case. Could your or Ale check out my branch in the kotlin project and give QA feedback? https://github.com/stakwork/sphinx-kotlin/pull/581

I will start work on Mac

**Comment by tomastiminskas** [comment]
@jimBeaux27 Perfect. I will check android tomorrow and will give you some feedback

**Pull request merged**
